import { readFile } from "node:fs/promises";

import type { Dependency } from "./npm";

/*
 * ============================================================
 * yarn.lock parser
 * ============================================================
 *
 * Supports both major formats:
 *
 * Yarn 1 (classic):
 *   # THIS IS AN AUTOGENERATED FILE...
 *   axios@^1.2.0, axios@^1.3.0:
 *     version "1.7.2"
 *     resolved "https://registry.yarnpkg.com/..."
 *
 * Yarn Berry (v2+):
 *   __metadata:
 *     version: 6
 *   "axios@npm:^1.2.0":
 *     version: 1.7.2
 *     resolution: "axios@npm:1.7.2"
 *
 * Parsed line-by-line — no YAML dependency needed.
 */

/**
 * Extract the package name from a yarn spec.
 *
 * Examples:
 *   axios@^1.2.0          → axios
 *   @babel/core@^7.0.0    → @babel/core
 *   axios@npm:^1.2.0      → axios (berry protocol)
 *   @scope/pkg@npm:^1     → @scope/pkg
 */
function specToName(
  rawSpec: string,
): string | null {
  let spec = rawSpec.trim();

  // Strip surrounding quotes
  spec = spec.replace(/^["']|["']$/g, "");

  if (!spec) {
    return null;
  }

  // Skip workspaces and non-registry protocols
  if (
    spec.startsWith("workspace:") ||
    spec.startsWith("workspace,") ||
    spec.includes("workspace:")
  ) {
    return null;
  }

  // Berry protocol form: name@npm:range
  const protocolIndex = spec.indexOf("@npm:");

  if (protocolIndex > 0) {
    return spec.slice(0, protocolIndex) || null;
  }

  // Classic form: split at last @ that is not
  // the leading scope marker (@scope/name@range)
  const atIndex = spec.lastIndexOf("@");

  if (atIndex <= 0) {
    return null;
  }

  return spec.slice(0, atIndex) || null;
}

export async function parseYarnLockfile(
  path: string,
): Promise<Dependency[]> {
  const raw =
    await readFile(path, "utf8");

  const lines = raw.split(/\r?\n/);

  const result =
    new Map<string, Dependency>();

  /*
   * Current entry state:
   * - specs: all alias specs pointing at one resolution
   * - version: resolved concrete version
   */
  let currentSpecs: string[] = [];
  let currentVersion: string | null = null;

  function flush(): void {
    if (
      currentSpecs.length === 0 ||
      !currentVersion
    ) {
      currentSpecs = [];
      currentVersion = null;
      return;
    }

    for (const spec of currentSpecs) {
      const name = specToName(spec);

      if (!name) {
        continue;
      }

      const dedupeKey =
        `${name}@${currentVersion}`;

      if (!result.has(dedupeKey)) {
        result.set(dedupeKey, {
          name,
          version: currentVersion!,
          source: "lockfile",
          dev: false,
        });
      }
    }

    currentSpecs = [];
    currentVersion = null;
  }

  for (const line of lines) {
    // Blank / comment lines never break an entry,
    // but a new header flushes the previous one.
    if (
      line.length === 0 ||
      line.startsWith("#")
    ) {
      continue;
    }

    const isIndented =
      line.startsWith(" ") ||
      line.startsWith("\t");

    if (!isIndented) {
      /*
       * Entry header line:
       *
       *   axios@^1.2.0, axios@^1.3.0:
       *   "axios@npm:^1.2.0":
       *
       * __metadata is not a package entry.
       */
      if (/^[^#].*:\s*$/.test(line)) {
        flush();

        const header = line.slice(
          0,
          line.lastIndexOf(":"),
        );

        currentSpecs = header
          .split(",")
          .map((spec) => spec.trim())
          .filter(Boolean);
      }

      continue;
    }

    const trimmed = line.trim();

    /*
     * Version lines:
     *   version "1.7.2"     (yarn 1)
     *   version: 1.7.2      (berry)
     */
    const versionMatch = trimmed.match(
      /^version[:\s]+["']?([^"'\s]+)["']?/,
    );

    if (versionMatch) {
      currentVersion = versionMatch[1];
    }
  }

  flush();

  return Array.from(result.values());
}
